export const IMAGE_PATH = "/uploads/";
export const EXCEL_EXPORT_PATH = "/uploads/export/products.xlsx";
export const EXCEL_IMPORT_PATH = "/uploads/import/import_products.xlsx";
export const ASSET_PATH = "/assets/";
export const APP_NAME = "Sundaymart";
export const DEV_MODE = true;
export const IS_DEMO = false;//make it false
export const GOOGLE_MAP_API_KEY="AIzaSyBFsAIXWFOG2FdhUnxbO9-VsJ2LlTezE98";
export const CHAT_CLIENT = "https://sundaymart.net:3001";
